### ISSUE TITLE
Remove using `pydantic`

### ISSUE THREAD

**Issue by markov-avl** [markov-avl/Puripy#29]
`pydantic` is used to make class as dataclass if it's marked with `@properties`. Need to write your own logic for filling such classes with properties from the configuration file. **`pydantic` should be removed from dependencies.**

Example:

properties.yaml:
```yaml
root:
  values:
    int_value: 1
    str_value: foo
    array_value:
      - element1
      - element2
    object_value:
      another-value: bar
```

client code:
```python
@properties(path="properties.yaml", prefix="root.values")
class Properties:

  class ObjectValue:
    another_value: str  # should be mapped correctly despite the replacement `-` with `_` in the key

  missing_value  # error it's missing
  int_value: int  # value shoud be converted to int
  str_value  # no conversions or type checks, this value just should exist
  array_value: list[str]  # generic type conversion
  object_value: ObjectValue  # it should be constructed from context
```
